import React from "react";

const GlobalContext = React.createContext({
  monthIndex: 0,
  setMonthIndex: (index) => {},
  smallCalendarMonth: 0,
  setSmallCalendarMonth: (index) => {},
  daySelected: null,
  setDaySelected: (day) => {},
  showEventModal: false,
  setShowEventModal: () => {},
  showDashBoard: false,
  isDayMode: false,
  setIsDayMode: () => {},
  setShowDashBoard: () => {},
  dispatchCalEvent: ({ type, payload }) => {},
  savedEvents: [],
  selectedEvent: null,
  setSelectedEvent: () => {},
  setLabels: () => {},
  labels: [],
  updateLabel: () => {},
  filteredEvents: [],
  refresh: true,
  setRefresh: () => {},
  showMore: false,
  setShowMore: () => {},
  labelList: {},
  setLabelList: () => {},
  userId: "",
  setUserId: () => {},
  dayModeEvents: [],
  setDayModeEvents: () => {},
});

export default GlobalContext;
